export let payload = [
    {
        id: '287172945',
        error: [
            'failed to find and account for date element in entry_detailes list',
            'Error with location',
            'Error with time/date splicing',
            'Error with time reformatting',
        ],
    },
    {
        dayofweek: 'Tuesday',
        timestart: 480,
        timestop: 1380,
        location: ["Well.. it's somewhere!"],
        title: 'Srct meeting',
        description: 'a meeting for MasonSRCT',
        month: 'March',
        year: '2018',
        id: '286116240',
        dayofmonth: '28',
    },
    {
        dayofweek: 'Tuesday',
        timestart: 720,
        timestop: 1439,
        location: ['Not Provided'],
        title: 'Selective Withdrawal Period',
        description: 'Undergraduate students only ',
        month: 'March',
        year: '2018',
        id: '284761355',
        dayofmonth: '28',
    },
];
